language: node_js
node_js:
  - 10

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 24db388b048125d3485275e736dba62c98106981
  keep_history: true
  on:
    branch: master
