language: node_js
node_js:
  - 10

branches:
  only:
    - master

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 2df1b30ce3e6fd06acf7bae96cbdc28984415367
  keep_history: true
  on:
    branch: master
