export default {
  ADD_ITEMS_TO_CART: 'ADD_ITEMS_TO_CART',

  SET_ORDER_STAGE: 'SET_ORDER_STAGE',
  UPDATE_SHIPPING: 'UPDATE_SHIPPING',
  SET_SHIPPING_LOCATION: 'SET_SHIPPING_LOCATION',
  UPDATE_BILLING: 'UPDATE_BILLING',
  SET_BILLING_LOCATION: 'SET_BILLING_LOCATION',
  UPDATE_PAYMENT: 'UPDATE_PAYMENT'
};
